// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekSiparisApp.Data;

#nullable disable

namespace YemekSiparisApp.Migrations
{
    [DbContext(typeof(YemekSiparisContext))]
    [Migration("20260413193559_IlkOlusturma")]
    partial class IlkOlusturma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.AskidaYemekBagis", b =>
                {
                    b.Property<int>("BagisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BagisId"));

                    b.Property<DateTime>("BagisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BagisciKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("HavuzId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnonim")
                        .HasColumnType("bit");

                    b.Property<string>("Mesaj")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BagisId");

                    b.HasIndex("BagisciKullaniciId");

                    b.HasIndex("HavuzId");

                    b.ToTable("AskidaYemekBagislari", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bagis_Miktar", "Miktar > 0");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.AskidaYemekHavuzu", b =>
                {
                    b.Property<int>("HavuzId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HavuzId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RestoranId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamBakiye")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("HavuzId");

                    b.HasIndex("RestoranId");

                    b.ToTable("AskidaYemekHavuzlari", null, t =>
                        {
                            t.HasCheckConstraint("CK_Havuz_Bakiye", "ToplamBakiye >= 0");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.AskidaYemekKullanim", b =>
                {
                    b.Property<int>("KullanimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullanimId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("HavuzId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<decimal>("KullanilanMiktar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("KullanimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("KullanimId");

                    b.HasIndex("HavuzId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SiparisId")
                        .IsUnique();

                    b.ToTable("AskidaYemekKullanimlari", null, t =>
                        {
                            t.HasCheckConstraint("CK_Kullanim_Miktar", "KullanilanMiktar > 0");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("IkonUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SiralamaNo")
                        .HasColumnType("int");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIhtiyacSahibi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("KullaniciId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefon")
                        .IsUnique();

                    b.ToTable("Kullanicilar", null, t =>
                        {
                            t.HasCheckConstraint("CK_Kullanicilar_Rol", "Rol IN ('Musteri','Admin','RestoranSahibi','Kurye')");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Kurye", b =>
                {
                    b.Property<int>("KuryeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KuryeId"));

                    b.Property<string>("AracTipi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Plaka")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Puan")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ToplamTeslimat")
                        .HasColumnType("int");

                    b.HasKey("KuryeId");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("Kuryeler", null, t =>
                        {
                            t.HasCheckConstraint("CK_Kuryeler_Durum", "Durum IN ('Musait','Mesgul','Offline')");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.MenuKalemi", b =>
                {
                    b.Property<int>("MenuKalemiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuKalemiId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HazirlamaSuresi")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAkti")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVejetaryen")
                        .HasColumnType("bit");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RestoranId")
                        .HasColumnType("int");

                    b.HasKey("MenuKalemiId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("RestoranId");

                    b.ToTable("MenuKalemleri", null, t =>
                        {
                            t.HasCheckConstraint("CK_MenuKalemleri_Fiyat", "Fiyat > 0");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Restoran", b =>
                {
                    b.Property<int>("RestoranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestoranId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MinSiparisUcreti")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Puan")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("PuanSayisi")
                        .HasColumnType("int");

                    b.Property<int>("SahipKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TahminiTeslimatDakika")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("ToplamCiro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RestoranId");

                    b.HasIndex("SahipKullaniciId")
                        .IsUnique();

                    b.ToTable("Restoranlar", null, t =>
                        {
                            t.HasCheckConstraint("CK_Restoranlar_Puan", "Puan IS NULL OR (Puan >= 1.0 AND Puan <= 5.0)");

                            t.HasCheckConstraint("CK_Restoranlar_ToplamCiro", "ToplamCiro >= 0");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Siparis", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsAskidaYemek")
                        .HasColumnType("bit");

                    b.Property<int?>("KuryeId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestoranId")
                        .HasColumnType("int");

                    b.Property<string>("SiparisNotu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeslimatAdresi")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("TeslimatUcreti")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SiparisId");

                    b.HasIndex("KuryeId");

                    b.HasIndex("MusteriKullaniciId");

                    b.HasIndex("RestoranId");

                    b.ToTable("Siparisler", null, t =>
                        {
                            t.HasCheckConstraint("CK_Siparisler_Durum", "Durum IN ('Beklemede','Onaylandi','Hazirlaniyor','YoldaKurye','TeslimEdildi','Iptal')");

                            t.HasCheckConstraint("CK_Siparisler_ToplamTutar", "ToplamTutar > 0");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.SiparisDetay", b =>
                {
                    b.Property<int>("SiparisDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisDetayId"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("MenuKalemiId")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<string>("Notlar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SiparisDetayId");

                    b.HasIndex("MenuKalemiId");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisDetaylari", null, t =>
                        {
                            t.HasCheckConstraint("CK_SiparisDetay_Miktar", "Miktar > 0");
                        });
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.AskidaYemekBagis", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.Kullanici", "BagisciKullanici")
                        .WithMany("AskidaYemekBagislari")
                        .HasForeignKey("BagisciKullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YemekSiparisApp.Models.Entities.AskidaYemekHavuzu", "Havuz")
                        .WithMany("Bagislar")
                        .HasForeignKey("HavuzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BagisciKullanici");

                    b.Navigation("Havuz");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.AskidaYemekHavuzu", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.Restoran", "Restoran")
                        .WithMany()
                        .HasForeignKey("RestoranId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Restoran");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.AskidaYemekKullanim", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.AskidaYemekHavuzu", "Havuz")
                        .WithMany("Kullanimlar")
                        .HasForeignKey("HavuzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSiparisApp.Models.Entities.Kullanici", "KullaniciKullanici")
                        .WithMany("AskidaYemekKullanimlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSiparisApp.Models.Entities.Siparis", "Siparis")
                        .WithOne("AskidaYemekKullanimi")
                        .HasForeignKey("YemekSiparisApp.Models.Entities.AskidaYemekKullanim", "SiparisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Havuz");

                    b.Navigation("KullaniciKullanici");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Kurye", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.Kullanici", "Kullanici")
                        .WithOne("KuryeBilgisi")
                        .HasForeignKey("YemekSiparisApp.Models.Entities.Kurye", "KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.MenuKalemi", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.Kategori", "Kategori")
                        .WithMany("MenuKalemleri")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSiparisApp.Models.Entities.Restoran", "Restoran")
                        .WithMany("MenuKalemleri")
                        .HasForeignKey("RestoranId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Restoran");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Restoran", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.Kullanici", "SahipKullanici")
                        .WithOne("SahipOlduguRestoran")
                        .HasForeignKey("YemekSiparisApp.Models.Entities.Restoran", "SahipKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SahipKullanici");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Siparis", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.Kurye", "Kurye")
                        .WithMany("Siparisler")
                        .HasForeignKey("KuryeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YemekSiparisApp.Models.Entities.Kullanici", "MusteriKullanici")
                        .WithMany("Siparisler")
                        .HasForeignKey("MusteriKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSiparisApp.Models.Entities.Restoran", "Restoran")
                        .WithMany("Siparisler")
                        .HasForeignKey("RestoranId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurye");

                    b.Navigation("MusteriKullanici");

                    b.Navigation("Restoran");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.SiparisDetay", b =>
                {
                    b.HasOne("YemekSiparisApp.Models.Entities.MenuKalemi", "MenuKalemi")
                        .WithMany("SiparisDetaylari")
                        .HasForeignKey("MenuKalemiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSiparisApp.Models.Entities.Siparis", "Siparis")
                        .WithMany("SiparisDetaylari")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuKalemi");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.AskidaYemekHavuzu", b =>
                {
                    b.Navigation("Bagislar");

                    b.Navigation("Kullanimlar");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Kategori", b =>
                {
                    b.Navigation("MenuKalemleri");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Kullanici", b =>
                {
                    b.Navigation("AskidaYemekBagislari");

                    b.Navigation("AskidaYemekKullanimlari");

                    b.Navigation("KuryeBilgisi");

                    b.Navigation("SahipOlduguRestoran");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Kurye", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.MenuKalemi", b =>
                {
                    b.Navigation("SiparisDetaylari");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Restoran", b =>
                {
                    b.Navigation("MenuKalemleri");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("YemekSiparisApp.Models.Entities.Siparis", b =>
                {
                    b.Navigation("AskidaYemekKullanimi");

                    b.Navigation("SiparisDetaylari");
                });
#pragma warning restore 612, 618
        }
    }
}
